### ISSUE TITLE
Called in wrong state: STATE_INPROGRESS / no mouse events firing?

### ISSUE THREAD

**Issue by benzmuircroft** [rtc-io/rtc-sharedcursor#4]
I can't get rtc-sharedcursor to work at all

If I use it along side an existing quickconnect (already running) connection then the cusors quickconnect makes this error 

```
setRemoteDescription task failed:  Failed to set remote answer sdp: Called in wrong state: STATE_INPROGRESS
```

but alternatively if i only have the rtc-sharedcursors quickconnect (that error goes away but) I get nothing coming through the data event (id,type,x,y) it never fires when i move over the blank document body

If I `console.dir` the cursor I see that there is indeed a data event listening

```
events: {data: EE},
attach: function (target) {},
detach: function () {}
```

So that must mean that events are not being sent

I have even tried to add the cursor data event inside the signaller.once connected event

```
we have successfully connected
peer cic8a2but0000354wmzua43ao has connected
new peer found in room:  Object {browser: "chrome", browserVersion: "41.0.2272", agent: "signaller@6.2.1", id: "cic8a2but0000354wmzua43ao", room: "hes-dead-jim"}
//nothing.....................(*wiggling mouse around*)
```

But no mouse movement events are getting sent (I think) 

What do you recon is/isn't happening?

**Comment by DamonOehlman** [comment]
@benzmuircroft Thanks for getting stuck in with rtc.io :) It's nice to see someone really explore all the things that were built over a long period of time.  I just did a quick check of the demo to make sure that shared cursor is still working, and as far as I can tell it is (screenshot below):

![2015-07-19-193252_1920x1080_scrot](https://cloud.githubusercontent.com/assets/609693/8765399/6acf27f0-2e4d-11e5-9fde-d63c6fef8c21.png)

In the first instance, where you are seeing the `STATE_INPROGRESS` error this will be because quickconnect is configured by default not to renegotiate connections once established, and `rtc-sharedcursor` is asking to do that when it requests that a new data channel is created just for it.  You can create your quickconnect objects in "reactive" mode (a very poorly documented feature, sorry) by creating them with like so:

``` js
var qc = quickconnect('https://switchboard.rtc.io/', {
  reactive: true
});
```

I'm not sure what is happening in the second case,  but it's possible it's something as simple as the document body having `0` width and height, so maybe try declaring some CSS to get it to equal 100% in both directions:

``` css
html, body {
  width: 100%;
  height: 100%;
  margin: 0;
}
```

**Comment by benzmuircroft** [comment]
Thanks, I read https://github.com/rtc-io/rtc-sharedcursor/issues/3 so I made my mind up to alter the code of rtc-mesh to support trading mouse cursor positions in https://github.com/rtc-io/rtc-mesh/issues/13 I have posted some of what I have done. This is really awesome stuff to build on!
